version: '3'

services:
  # cache:
  #   image: redis
  api:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: bash init.sh
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    # depends_on:
    #   - cache